### ISSUE TITLE
MSX2 or 2+ support

### ISSUE THREAD

**Issue by Lisias** [santiontanon/transballmsx#1]
Hi.

Would you consider a MSX2+ version? Some MSX2+ have a "turbo mode" (as the Panasonic WX, some brazilian clones/hacks and FPGA implementations), and that would be of good use on your game.

A joint effort would be useful, some guys from Brazil enjoyed your work very much (me included).

**Comment by santiontanon** [comment]
Thanks for the suggestion (and the nice comments!). Yes! I would indeed like to do an MSX2 version. It might take me a while to get to it though, but it's definitively in my to-do list!

**Comment by artrag** [comment]
Hi would you consider to add in game voice samples?
I can provide you a very simple and efficient voice player working on the isr at 50 or 60 hz

**Comment by artrag** [comment]
This is  a sample file

**Comment by santiontanon** [comment]
At least I'd be very interested in playing around with it. The SFX I currently use for level start is a bit unsatisfying, and I have not added yet any SFX for level complete. So, those two could be good uses for voice samples. I might have to expand the size of the ROM though. Currently I'm trying to fit everything in a 32KB ROM and I only have about 600 bytes left of free space. But I could go to a 48KB one that would leave plenty of space :)

**Comment by artrag** [comment]
Going to email you some code using mrc in 1h

**Comment by artrag** [comment]
You have all the files on mrc

**Comment by artrag** [comment]
If you have time give a glance to mrc, wyz and me are adding speech to
salamander.
About 48KB and 64KB roms you can look at the sources of Deep Dungeon
Adventure (on mrc) and of Uridium on githhub
AR
Il 02/lug/2016 18:54, "santiontanon" notifications@github.com ha scritto:

**Comment by santiontanon** [comment]
Version 1.2 has support for MSX2 (smooth scroll). So, I'm going to close this issue. But any more requests are more than welcome! :)
